language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install git+https://github.com/a-maliarov/pyaction

before_script:
  - pip install coverage
  - pip install codecov

script:
  - coverage run tests/test_pyaction.py

after_success:
  - codecov
