__title__ = 'pyaction'
__description__ = 'Making life easier by being organized.'
__url__ = 'https://github.com/a-maliarov/pyaction'
__version__ = '0.0.2'
__author__ = 'Anatolii Maliarov'
__author_email__ = 'tly.mov@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Anatolii Maliarov'
